version: "3.8"
services:
  coldfusion:
    container_name: coldfusion-staging
    image: ghcr.io/${GITHUB_REPOSITORY}:develop
    ports:
      - "8555:8500"
    environment:
      - acceptEULA=YES
      - password=${CF_PASSWORD}
      - CF_ENV=staging
    volumes:
      - ./app:/app
      - ./staging-config:/opt/coldfusion/cfusion/lib
    networks:
      - staging_network
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/test.cfm"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    container_name: mysql-staging
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3333:3306"
    volumes:
      - ./mysql-data-staging:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - staging_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx-staging
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf
      - ./ssl/staging:/etc/nginx/ssl
    networks:
      - staging_network
    depends_on:
      - coldfusion
    restart: unless-stopped

networks:
  staging_network:
    driver: bridge
